### ISSUE TITLE
news.google.com字体渲染会把图标渲染成文字。

### ISSUE THREAD

**Issue by nlzqg** [F9y4ng/GreasyFork-Scripts#277] opened 2023-10-26 11:39 UTC
## 2. news.google.com字体渲染会把图标渲染成文字。

复现.(https://news.google.com/stories/CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lWcW8tX0NSRUJmQzJKTlBXMVNpZ0FQAQ?hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant)"_

![Snipaste_2023-10-26_18-24-18](https://github.com/F9y4ng/GreasyFork-Scripts/assets/140367049/d682445f-eda6-423c-a01b-76e8d8371a5b)
![Snipaste_2023-10-26_18-24-00](https://github.com/F9y4ng/GreasyFork-Scripts/assets/140367049/2b5cbbbe-1b65-495a-b9aa-1877b334babe)

**Comment by F9y4ng** [comment] 2023-10-26 15:56
Duplicate of #42

**Closed by F9y4ng** 2023-10-26 15:56 UTC
