### ISSUE TITLE
ios上百度搜索没有出现按钮

### ISSUE THREAD

**Issue by xiaoyuhaoge** [F9y4ng/GreasyFork-Scripts#275] opened 2023-10-26 05:15 UTC
不管是使用Userscripts还是stay，百度的这个界面不会出现跳转搜索按钮，脚本已更新至最新
![IMG_0889](https://github.com/F9y4ng/GreasyFork-Scripts/assets/134502767/ab26dff5-9d2a-4a43-b3fd-e0cd367fb565)
![IMG_0890](https://github.com/F9y4ng/GreasyFork-Scripts/assets/134502767/4425a4cf-8658-4ba3-81f8-408a4995f63c)
![IMG_0891](https://github.com/F9y4ng/GreasyFork-Scripts/assets/134502767/af3cd847-4c5c-4c9d-abc7-66ce2d2b1798)

**Comment by F9y4ng** [comment] 2023-10-26 06:04
Duplicate of #273

**Closed by F9y4ng** 2023-10-26 06:04 UTC
