### ISSUE TITLE
B站弹幕阴影没了

### ISSUE THREAD

**Issue by LRJuuu** [F9y4ng/GreasyFork-Scripts#410] opened 2024-12-25 07:10 UTC
如图是我的设置 关了脚本就正常了
开了脚本的效果：
![PixPin_2024-12-25_15-07-20](https://github.com/user-attachments/assets/21addf21-bcf6-4f25-80bf-a4d6b5abd83c)
![PixPin_2024-12-25_15-08-40](https://github.com/user-attachments/assets/97402c43-fda8-4b2e-a367-1663028a2041)
关了脚本的效果：
![PixPin_2024-12-25_15-09-11](https://github.com/user-attachments/assets/4d47e2c7-cf55-4e42-bdc5-02d024b39f90)

**Comment by F9y4ng** [comment] 2024-12-25 07:14
Duplicate of #42

**Closed by F9y4ng** 2024-12-25 07:14 UTC
